// app/layout.js
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import ReduxProvider from "@/lib/ReduxProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" />
      </head>
      <body style={{ fontFamily: '"Work Sans", sans-serif' }}>
        <ReduxProvider>
          <AntdRegistry>
            {children}
          </AntdRegistry>
        </ReduxProvider>
      </body>
    </html>
  );
}
